#!/bin/bash

cd /usr/src/homeassistant
for integration in `find /config/custom_components -mindepth 1 -maxdepth 1 -type d`
do
    python -m script.hassfest --action validate --integration-path $integration
done